=== hosseinfani/data_odyssey/Project/Moviesion04/MoviesionData.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="MoviesionData">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="Movie"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="Director"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="PK_Movie_Id">
			<xs:selector xpath="Movie"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:key name="PK_Director_Id">
			<xs:selector xpath="Director"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:keyref name="FK_Movie_DirectorId_2_Director_Id" refer="PK_Director_Id">
			<xs:selector xpath="Movie"/>
			<xs:field xpath="@DirectorId"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="Movie">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="Title"/>
				<xs:element type="xs:string" name="Genre"/>
				<xs:element type="xs:decimal" name="RunningTime"/>
				<xs:element type="xs:date" name="ReleaseDate"/>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:integer" use="required"/>
			<xs:attribute name="DirectorId" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Director">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="FirstName"/>
				<xs:element type="xs:string" name="LastName"/>
				<xs:element type="xs:date" name="DateOfBirth"/>
				<xs:element type="xs:string" name="PlaceOfBirth"/>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:integer" use="required"/>
		</xs:complexType>		
	</xs:element>
</xs:schema>

=== hosseinfani/data_odyssey/Project/Moviesion04/MoviesionData_ExternalXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<MoviesionData xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation= "MoviesionData.xsd">
    <Movie Id="1" DirectorId="1">
        <Title>Inception</Title>
        <Genre>Mystery</Genre>
        <RunningTime>148</RunningTime>
        <ReleaseDate>2010-07-08</ReleaseDate>
    </Movie>
    <Movie Id="2" DirectorId="2">
        <Title>Avatar</Title>
        <Genre>Sci-fi</Genre>
        <RunningTime>161</RunningTime>
        <ReleaseDate>2009-12-10</ReleaseDate>
    </Movie>
    <Director Id="1">
        <FirstName>Christopher</FirstName>
		<LastName>Nolan</LastName>
        <DateOfBirth>1970-06-30</DateOfBirth>
        <PlaceOfBirth>England</PlaceOfBirth>
    </Director>
    <Director Id="2">
        <FirstName>James</FirstName>
		<LastName>Cameron</LastName>
        <DateOfBirth>1954-08-16</DateOfBirth>
        <PlaceOfBirth>Canada</PlaceOfBirth>
    </Director>
</MoviesionData>
